### ISSUE TITLE
wrong stdin check for -2 option

### ISSUE THREAD

**Issue by zsalvet** [shenwei356/seqkit#102]
seqkit sample -2 ... returns error
      "two-pass mode (-2) will failed when reading from stdin. please disable flag: -2"
when stdin is not a character device (e.g. pipe) regardless whether input is going
to be read from stdin actually or not. Type of stdin file descriptor should be of no consequence here,
you had better check if number of input records differs between passes.

**Comment by shenwei356** [comment]
> Type of stdin file descriptor should be of no consequence here

I don't get it. I though I've taken all the cases into consideration.

```
$ cat ../tests/hairpin.fa | seqkit sample -n 1 -2 -
[INFO] sample by number
[ERRO] two-pass mode (-2) will failed when reading from stdin. please disable flag: -2

$ cat ../tests/hairpin.fa | seqkit sample -n 1 -2 
[INFO] sample by number
[ERRO] two-pass mode (-2) will failed when reading from stdin. please disable flag: -2

$ seqkit sample -n 1 -2 -
[INFO] sample by number
[INFO] first pass: counting seq number
[INFO] seq number: 0
[INFO] second pass: reading and sampling
[ERRO] fastx: stdin not detected
```

**Comment by zsalvet** [comment]
Please try 
cat /dev/null | seqkit sample -2 --number 2000000 --rand-seed 10 -o Asample -w 0 Ainput

**Comment by zsalvet** [comment]
If filename different than "-" is given, it should not worry about stdin
(it could be anything when seqkit is called from another script rather than manually from terminal).

**Comment by shenwei356** [comment]
Yes, you're right, I've fixed it. Thank you!


- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4098359/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4098360/seqkit_linux_amd64.tar.gz)

**Comment by zsalvet** [comment]
Thanks, good enough for my use.
But I think the "xopen.IsStdin()" part of the condition is still wrong, you had better remove it.
stdin or not, nothing else is relevant. (See implementation of xopen.IsStdin, you may be thinking it does
something else than it really does...)

**Comment by shenwei356** [comment]
Thank you! Fixed:

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4098648/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4098649/seqkit_linux_amd64.tar.gz)

**Comment by poojap837** [comment]
seqkit fa2fq -f *.fa
[INFO] 2192 sequences loaded
[ERRO] fastx: stdin not detected

Could you please check and let me know what changes I should make?

**Comment by shenwei356** [comment]
> [ERRO] fastx: stdin not detected

No input file or stdin is detected.

It should be

    seqkit fa2fq -f small.fa big.fq -o small.fq

**Comment by plijnzaad** [comment]
This still doesn't work:


```
$ seqkit fa2fq -w 60  -f PBM11090_pass_f7cf4b5f_8bda2ae4_11-GT100k.fastq.gz  -o wrapped.fa   
[INFO] 1 sequences loaded
[ERRO] fastx: stdin not detected
```

This is 

```
$ seqkit version

seqkit v2.13.0
```
